### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by guimard** [cyrusimap/cyrus-timezones#3]
Hi,

trying to compile this library, I got this:
```
./configure: line 8646: syntax error near unexpected token `ICAL,'
./configure: line 8646: `PKG_CHECK_MODULES(ICAL, libical)'
```
libical is installed in version 3.0.7 with its headers

**Comment by ajaysusarla** [comment]
@guimard my guess is that `libical` is not being found in your path.

One can do a quick check to see if `libical` is indeed available in your path(such that `PKGCONFIG` can find it) by running:
`$ pkg-config --cflags --libs  "libical"`

On my machine I get:

```
$ pkg-config --cflags --libs  "libical"
-lical -licalss -licalvcal 
```

**Comment by guimard** [comment]
Hi,
glib-2.0 headers were missing.
